services:
  gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - authentication-service
      - user-service

  authentication-service:
    build:
      context: ./authentication_service

    container_name: authentication-service

    ports:
      - "8000:8000"
    env_file:
      - ./authentication_service/.env
    volumes:
      - ./authentication_service:/authentication_service
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  user-service:
    build:
      context: ./user_service

    container_name: user-service

    ports:
      - "8005:8005"
    env_file:
      - ./user_service/.env
    volumes:
      - ./user_service:/user_service
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8005"
      - --reload
  admin-service:
    build:
      context: ./admin_service
    container_name: admin-service
    ports:
      - "8002:8002"
    env_file:
      - ./admin_service/.env
    volumes:
      - ./admin_service:/admin_service
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8002"
      - --reload
  menu-service:
    build:
      context: ./menu_service
    container_name: menu-service
    ports:
      - "8001:8001"
    env_file:
      - ./menu_service/.env
    volumes:
      - ./menu_service:/menu_service
      - ./menu_service/app/templates_menu/media:/menu_service/app/templates/media
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8001"
      - --reload
  reservation-service:
    build:
      context: ./reservation_service
    container_name: reservation-service
    ports:
      - "8003:8003"
    env_file:
      - ./reservation_service/.env
    volumes:
      - ./reservation_service:/reservation_service
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8003"
      - --reload
  support-service:
    build:
      context: ./support_service
    container_name: support-service
    ports:
      - "8006:8006"
    env_file:
      - ./support_service/.env
    volumes:
      - ./support_service:/support_service
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8006"
      - --reload
  order-service:
    build:
      context: ./order_service
    container_name: order-service
    ports:
      - "8007:8007"
    env_file:
      - ./order_service/.env
    volumes:
      - ./order_service:/order_service
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8007"
      - --reload

  db-authentication:
    image: postgres:16
    container_name: db-authentication
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
  db-user:
    image: postgres:16
    container_name: db-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
  db-admin:
    image: postgres:16
    container_name: db-admin
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_bar_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data
  db-menu:
    image: postgres:16
    container_name: db-menu
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menu_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_menu_data:/var/lib/postgresql/data
  db-reservation:
    image: postgres:16
    container_name: db-reservation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_reservation_data:/var/lib/postgresql/data
  db-support:
    image: postgres:16
    container_name: db-support
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_db
    ports:
      - "5437:5432"
    volumes:
      - postgres_support_data:/var/lib/postgresql/data
  db-order:
    image: postgres:16
    container_name: db-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
volumes:
  postgres_auth_data:
  postgres_user_data:
  postgres_admin_data:
  postgres_menu_data:
  postgres_reservation_data:
  postgres_support_data:
  postgres_order_data: