server {
    listen 80;

    location /login {
        proxy_pass http://authentication-service:8000;
    }

    location /registration {
        proxy_pass http://authentication-service:8000;
    }

    location /user/my_profile {
        proxy_pass http://user-service:8005;
    }

    location /logout {
        proxy_pass http://user-service:8005;
    }

    location /user/edit {
        proxy_pass http://user-service:8005;
    }

    location /bar_name {
        proxy_pass http://authentication-service:8000;
    }

    location /user/delete {
        proxy_pass http://user-service:8005;
    }

    location /user/password {
        proxy_pass http://user-service:8005;
    }

    location /edit_email {
        proxy_pass http://authentication-service:8000;
    }

    location /edit_password {
        proxy_pass http://authentication-service:8000;
    }
}