server {
    listen 80;

    location /login {
        proxy_pass http://authentication-service:8000;
    }

    location /get_all_users {
        proxy_pass http://authentication-service:8000;
    }

    location /registration {
        proxy_pass http://authentication-service:8000;
    }

    location /user/my_profile {
        proxy_pass http://user-service:8005;
    }

    location /logout {
        proxy_pass http://user-service:8005;
    }

    location /user/edit {
        proxy_pass http://user-service:8005;
    }

    location /bar_name {
        proxy_pass http://authentication-service:8000;
    }

    location /user/delete {
        proxy_pass http://user-service:8005;
    }

    location /user/password {
        proxy_pass http://user-service:8005;
    }

    location /edit_email {
        proxy_pass http://authentication-service:8000;
    }

    location /edit_password {
        proxy_pass http://authentication-service:8000;
    }

    location /admin/login {
        proxy_pass http://authentication-service:8000;
    }

    location /admin/registration {
        proxy_pass http://authentication-service:8000;
    }

    location  /admin_panel/edit/ {
        proxy_pass http://admin-service:8002;
    }

    location  /admin_panel/all_admins/add_admin {
        proxy_pass http://admin-service:8002;
    }

    location  /admin_panel/all_admins {
        proxy_pass http://admin-service:8002;
    }

    location  /admin_panel {
        proxy_pass http://admin-service:8002;
    }

    location  /admin/logout {
        proxy_pass http://admin-service:8002;
    }

    location  /menu_page {
        proxy_pass http://menu-service:8001;
    }

    location /media/ {
    proxy_pass http://menu-service:8001;
}

    location /tables {
    proxy_pass http://reservation-service:8003;
}

    location /support {
    proxy_pass http://support-service:8006;
}

    location /ws/support/ {
    proxy_pass http://support-service:8006;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
}


}