"""changed birthday columntype from datetime to date

Revision ID: 3a598afa7952
Revises: 86229b056be8
Create Date: 2026-08-19 18:06:28.186509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a598afa7952'
down_revision: Union[str, Sequence[str], None] = '86229b056be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('admin', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MODERATOR', name='role'),
               type_=sa.Enum('ADMIN', 'MODERATOR', name='adminrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'role',
               existing_type=sa.Enum('ADMIN', 'MODERATOR', name='adminrole'),
               type_=postgresql.ENUM('ADMIN', 'MODERATOR', name='role'),
               existing_nullable=False)
    op.alter_column('admin', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
